language: python

matrix:
  include:
    - python: '3.6'
      os: linux
      env: USE_OMP=0
      install:
      - pip install cython
      - python setup.py install
    - python: '3.6'
      os: linux
      env: USE_OMP=1 OMP_NUM_THREADS=4
      install:
      - pip install cython
      - python setup.py install
    - python: '3.7'
      os: linux
      env: USE_OMP=0
      install:
      - pip install cython
      - python setup.py install
      script: python setup.py test
    - python: '3.7'
      os: linux
      env: USE_OMP=1 OMP_NUM_THREADS=4
      install:
      - pip install cython
      - python setup.py install
    - python: '3.8'
      os: linux
      env: USE_OMP=0
      install:
      - pip install cython
      - python setup.py install
    - python: '3.8'
      os: linux
      env: USE_OMP=1 OMP_NUM_THREADS=4
      install:
      - pip install cython
      - python setup.py install
    - python: '3.9'
      os: linux
      env: USE_OMP=0
      install:
      - pip install cython
      - python setup.py install
      script: python setup.py test
    - python: '3.9'
      os: linux
      env: USE_OMP=1 OMP_NUM_THREADS=4
      install:
      - pip install cython
      - python setup.py install
    - os: osx
      language: shell  # 'language: python' is an error on Travis CI macOS
      env: USE_OMP=0
      before_install:
        - python --version
        - pip install cython --user
      install:
      - pip install . --user
      script: python setup.py test
    - os: osx
      language: shell  # 'language: python' is an error on Travis CI macOS
      env: USE_OMP=1 OMP_NUM_THREADS=4
      before_install:
        - python --version
        - pip install cython --user
      install:
      - pip install . --user
    - os: windows
      language: shell  # 'language: python' is an error on Travis CI windows
      env: USE_OMP=0
      before_install:
        - python --version
        - pip install cython
      install:
        - pip install .
      script: python setup.py test
    - os: windows
      language: shell  # 'language: python' is an error on Travis CI windows
      env: USE_OMP=1 OMP_NUM_THREADS=4
      before_install:
        - python --version
        - pip install cython
      install:
        - pip install .


script: python setup.py test 
