language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'

os:
  - linux
  - osx
  - windows

env:
- USE_OMP=0
- USE_OMP=1 OMP_NUM_THREADS=4

install:
- pip install cython
- python setup.py install

script: python setup.py test 
